export const countriesImages: any = {
  australia: require('../assets/countries/australia.png'),
  austria: require('../assets/countries/austria.png'),
  azerbaijan: require('../assets/countries/azerbaijan.png'),
  bahrain: require('../assets/countries/bahrain.png'),
  belgium: require('../assets/countries/belgium.png'),
  brazil: require('../assets/countries/brazil.png'),
  canada: require('../assets/countries/canada.png'),
  france: require('../assets/countries/france.png'),
  hungary: require('../assets/countries/hungary.png'),
  italy: require('../assets/countries/italy.png'),
  japan: require('../assets/countries/japan.png'),
  mexico: require('../assets/countries/mexico.png'),
  monaco: require('../assets/countries/monaco.png'),
  netherlands: require('../assets/countries/netherlands.png'),
  saudiarabia: require('../assets/countries/saudi-arabia.png'),
  singapore: require('../assets/countries/singapore.png'),
  spain: require('../assets/countries/spain.png'),
  uae: require('../assets/countries/uae.png'),
  uk: require('../assets/countries/uk.png'),
  usa: require('../assets/countries/usa.png'),
}

export const driversImages: any = {
  albon: require('../assets/drivers/albon.png'),
  alonso: require('../assets/drivers/alonso.png'),
  bottas: require('../assets/drivers/bottas.png'),
  de_vries: require('../assets/drivers/de_vries.png'),
  gasly: require('../assets/drivers/gasly.png'),
  hamilton: require('../assets/drivers/hamilton.png'),
  hulkenberg: require('../assets/drivers/hulkenberg.png'),
  kevin_magnussen: require('../assets/drivers/kevin_magnussen.png'),
  latifi: require('../assets/drivers/latifi.png'),
  leclerc: require('../assets/drivers/leclerc.png'),
  max_verstappen: require('../assets/drivers/max_verstappen.png'),
  mick_schumacher: require('../assets/drivers/mick_schumacher.png'),
  norris: require('../assets/drivers/norris.png'),
  ocon: require('../assets/drivers/ocon.png'),
  perez: require('../assets/drivers/perez.png'),
  ricciardo: require('../assets/drivers/ricciardo.png'),
  russell: require('../assets/drivers/russell.png'),
  sainz: require('../assets/drivers/sainz.png'),
  stroll: require('../assets/drivers/stroll.png'),
  tsunoda: require('../assets/drivers/tsunoda.png'),
  vettel: require('../assets/drivers/vettel.png'),
  zhou: require('../assets/drivers/zhou.png'),
}

export const driversFrontImages: any = {
  albon: require('../assets/drivers/albon_front.png'),
  alonso: require('../assets/drivers/alonso_front.png'),
  bottas: require('../assets/drivers/bottas_front.png'),
  de_vries: require('../assets/drivers/de_vries_front.png'),
  gasly: require('../assets/drivers/gasly_front.png'),
  hamilton: require('../assets/drivers/hamilton_front.png'),
  hulkenberg: require('../assets/drivers/hulkenberg_front.png'),
  kevin_magnussen: require('../assets/drivers/kevin_magnussen_front.png'),
  latifi: require('../assets/drivers/latifi_front.png'),
  leclerc: require('../assets/drivers/leclerc_front.png'),
  max_verstappen: require('../assets/drivers/max_verstappen_front.png'),
  mick_schumacher: require('../assets/drivers/mick_schumacher_front.png'),
  norris: require('../assets/drivers/norris_front.png'),
  ocon: require('../assets/drivers/ocon_front.png'),
  perez: require('../assets/drivers/perez_front.png'),
  ricciardo: require('../assets/drivers/ricciardo_front.png'),
  russell: require('../assets/drivers/russell_front.png'),
  sainz: require('../assets/drivers/sainz_front.png'),
  stroll: require('../assets/drivers/stroll_front.png'),
  tsunoda: require('../assets/drivers/tsunoda_front.png'),
  vettel: require('../assets/drivers/vettel_front.png'),
  zhou: require('../assets/drivers/zhou_front.png'),
}

export const circuitsImages: any = {
  albert_park: require('../assets/circuits/albert_park.png'),
  americas: require('../assets/circuits/americas.png'),
  bahrain: require('../assets/circuits/bahrain.png'),
  baku: require('../assets/circuits/baku.png'),
  catalunya: require('../assets/circuits/catalunya.png'),
  hungaroring: require('../assets/circuits/hungaroring.png'),
  imola: require('../assets/circuits/imola.png'),
  interlagos: require('../assets/circuits/interlagos.png'),
  jeddah: require('../assets/circuits/jeddah.png'),
  miami: require('../assets/circuits/miami.png'),
  monaco: require('../assets/circuits/monaco.png'),
  monza: require('../assets/circuits/monza.png'),
  red_bull_ring: require('../assets/circuits/red_bull_ring.png'),
  ricard: require('../assets/circuits/ricard.png'),
  rodriguez: require('../assets/circuits/rodriguez.png'),
  silverstone: require('../assets/circuits/silverstone.png'),
  marina_bay: require('../assets/circuits/marina_bay.png'),
  spa: require('../assets/circuits/spa.png'),
  suzuka: require('../assets/circuits/suzuka.png'),
  villeneuve: require('../assets/circuits/villeneuve.png'),
  yas_marina: require('../assets/circuits/yas_marina.png'),
  zandvoort: require('../assets/circuits/zandvoort.png'),
}
